Algoritmo "alturas"
// 

Var

nome, nome1 : caracter
altura, altura1 : caracter


Inicio

escreva ("nome da primeira pessoa: ")
leia (nome)
escreva ("altura da primeira pessoa: ")
leia(altura)

escreva ("nome da segunda pessoa: ")
leia (nome1)
escreva ("altura da segunda pessoa: ")
leia (altura1)

se (altura>altura1) entao
escreva ("o maior é: " + nome)
senao
escreva ("o maior é: " + nome1)

fimse
Fimalgoritmo