Algoritmo "quanto_já_viveu"
// 
Var

nome : caracter
idade : inteiro
anoatual : inteiro
dias : inteiro

Inicio

anoatual <- 2020
dias <- 365
escreva ("digite seu nome: ")
leia (nome)
escreva ("digite sua idade: ")
leia (idade)

idade <- (idade ' dias)
escreva ("o numero de dias que você já viveu é: " , idade)

anoatual <- (anoatual ' dias)
escreva ("o numero de sua idade é: " , idede)

Fimalgoritmo