Algoritmo "vetores_e_soma_de_vetores_atv1,2"
// 
Var

vet1 : vetor[1..5] de inteiro
vet2 : vetor[1..5] de inteiro
vet3 : vetor[1..5] de inteiro
contador : inteiro

Inicio

para contador de 1 ate 5 faca
escreva ("Digite um numero: ")
leia(vet1[contador])
vet2[contador] <- vet1[contador]
fimpara

escreval("  ")
escreval ("Listagem - vetor 1 e vetor 2 ")

vet3[contador] <- vet1[contador] + vet2[contador]


Fimalgoritmo